language: python
python:
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: ls
# command to run tests, e.g. python setup.py test
script: "py.test ."